### ISSUE TITLE
Fix modal centering of menu item

### ISSUE THREAD

**Issue by alvarotorrestx** [rvalde28/restaurant#1]
Modal needs to be centered to middle of screen on all screen sizes

Desktop: 
![image](https://github.com/user-attachments/assets/73719531-bbd8-4e4e-98dc-8d3aff3f9603)

Tablet:
![image](https://github.com/user-attachments/assets/482cd535-c9ba-4bb2-a767-e504716edf70)

Mobile:
![image](https://github.com/user-attachments/assets/ecbc44c1-c43a-4d14-b5ce-99fff5103536)

**Comment by rvalde28** [comment]
yes another issue :( I really didnt know how to do what I had planned for the modal on mobile views. So for desktop view. I wanted the modal to be 'attached' to the checkout/cart button.

![image](https://github.com/user-attachments/assets/d4525814-8f5d-4cef-8fff-6cf8191025eb)

for mobile it would be a 'page' as part of the menu/nav bar that we need to fix :( but for this I am open for suggestions because I really dont know what would be best. I like the idea of having a 'preview' before going to checkout, so id like to keep that concept. But as for the implementation I am down fro suggestions

**Comment by alvarotorrestx** [comment]
ohh I completely understand! Kind of simiilar to how most Shopify stores have their carts? Pop out and also a page?
My apologies, I now get what you were trying to do with it haha and I totally centered it. Now that I know, I have a better idea.

**Comment by alvarotorrestx** [comment]
Here's one side popup version:
![image](https://github.com/user-attachments/assets/432afc38-1bd5-4ee0-9768-4f9ce701e114)

Similarly:
![image](https://github.com/user-attachments/assets/818ccf32-f707-4eef-a9a7-dfe54b2fdad0)

But with the items visible correct?

and for mobile (maybe this, but full page view?) - this can be a popup or a redirect to page if you prefer:
![image](https://github.com/user-attachments/assets/b9d0e5de-7e09-4306-990a-9ae48e57b25f)

What are your thoughts? @rvalde28
